image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:19.03.0-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker version
  - docker-compose version
  - apk add --no-cache git coreutils
  - wget -O /usr/local/bin/git-restore-timestamp https://raw.githubusercontent.com/nishidayuya/git-restore-timestamp/master/exe/git-restore-timestamp
  - chmod a+x /usr/local/bin/git-restore-timestamp
  - git restore-timestamp

build:
  stage: build
  artifacts:
    paths:
      - outputs/
  cache:
    paths:
      - mruby/
  script:
    - docker-compose run compile
    - mkdir -pv outputs/
    - |
      for d in mruby/build/*/bin
      do
        target=$(echo $d | xargs dirname | xargs basename)
        echo $target
        mkdir -pv outputs/$target/
        cp -av mruby/build/$target/bin/* outputs/$target/
      done

mtest:
  stage: test
  cache:
    paths:
      - mruby/
  script:
    - docker-compose run mtest

bintest:
  stage: test
  cache:
    paths:
      - mruby/
  script:
    - docker-compose run bintest
