image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:19.03.0-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  artifacts:
    paths:
      - outputs/
  script:
    - docker version
    - docker-compose version
    - docker-compose run compile
    - mkdir -pv outputs/
    - |
      for d in mruby/build/*/bin
      do
        target=$(echo $d | xargs dirname | xargs basename)
        echo $target
        mkdir -pv outputs/$target/
        cp -av mruby/build/$target/bin/* outputs/$target/
      done
